services:
    server:
        container_name: recipe-server
        build:
            context: .
        ports:
            - $PORT:$PORT
        # env_file:
        #   - .env
        environment:
            SECRET_KEY: $SECRET_KEY
            
            DB_HOSTNAME: $DOCKER_DB_HOSTNAME
            DB_PORT: $DB_PORT
            DB_NAME: $DB_NAME
            DB_USERNAME: $DB_USERNAME
            DB_PASSWORD: $DB_PASSWORD

            EMAIL_USER: $EMAIL_USER
            EMAIL_PASSWORD: $EMAIL_PASSWORD

            RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
            RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
            RABBITMQ_HOST: $RABBITMQ_HOST
            RABBITMQ_PORT: $RABBITMQ_PORT

        # command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 # for production
        # command: python manage.py runserver # for development
    
    # celery-worker:
    #   container_name: celery-worker
    #   build: .
    #   user: appuser
    #   environment:
    #     SECRET_KEY: $SECRET_KEY
    #     DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1]
    #   command: celery -A config.celery worker --loglevel=info

    #   depends_on:
    #     - server
    #     - rabbitmq

    pg-db:
        image: postgres:15
        container_name: $DOCKER_DB_HOSTNAME
        restart: always
        environment:
            POSTGRES_USER: $DB_USERNAME
            POSTGRES_PASSWORD: $DB_PASSWORD
            PGDATA: /var/lib/postgresql/data/db-files/
            POSTGRES_DB: $DB_NAME
        ports:
            - "5434:5434"
        command: postgres -p 5434 -c 'max_connections=100'
        volumes:
            - ./pgdata/db-files:/var/lib/postgresql/data/db-files

        healthcheck:
            test: ["CMD", "pg_isready"]
            interval: 10s
            timeout: 5s
            retries: 5

    rabbitmq:
      image: rabbitmq:3.11.4-management
      container_name: 'rabbitmq'
      restart: always
      environment:
        RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
        RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
      ports:
        - 15672:15672
        - 5672:5672
